# -*- coding: utf-8 -*-
"""MNIST classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1svmKud37dY9ZQbF9awaPDvgl57avTdzF
"""

import streamlit as st
from streamlit_drawable_canvas import st_canvas
import numpy as np
import cv2  # OpenCV for image processing
from tensorflow.keras.models import load_model
import tensorflow as tf

# Set page config
st.set_page_config(page_title="MNIST Classifier", layout="wide")

# Load the trained MNIST model
# Use @st.cache_resource to load the model only once
@st.cache_resource
def load_mnist_model():
    try:
        model = load_model('mnist_cnn_model.h5')
        return model
    except (IOError, tf.errors.HDF5Error) as e:
        st.error(f"Error loading model 'mnist_cnn_model.h5': {e}")
        st.error("Please make sure the 'mnist_cnn_model.h5' file is in the same directory as this app.")
        return None

model = load_mnist_model()

# --- App Layout ---
st.title("🧠 MNIST Handwritten Digit Classifier")
st.write(
    "This is a web app to classify handwritten digits from 0-9. "
    "Draw a digit in the box below and click 'Predict'!"
)

# Create two columns
col1, col2 = st.columns(2)

with col1:
    st.header("Draw your digit here:")

    # Create a 280x280 canvas for drawing
    canvas_result = st_canvas(
        fill_color="rgba(255, 165, 0, 0.3)",  # Fixed fill color
        stroke_width=20,  # Pen size
        stroke_color="#FFFFFF",  # Pen color (white)
        background_color="#000000",  # Background color (black)
        height=280,
        width=280,
        drawing_mode="freedraw",
        key="canvas",
    )

with col2:
    st.header("Prediction:")

    if st.button("Predict"):
        if canvas_result.image_data is not None and model is not None:
            # 1. Get the image data from the canvas (it's RGBA)
            img = canvas_result.image_data.astype(np.uint8)

            # 2. Convert to Grayscale
            img_gray = cv2.cvtColor(img, cv2.COLOR_RGBA2GRAY)

            # 3. Resize to 28x28 (the size MNIST was trained on)
            # We use INTER_AREA interpolation, which is good for shrinking
            img_resized = cv2.resize(img_gray, (28, 28), interpolation=cv2.INTER_AREA)

            # 4. Normalize the image
            # The model was trained on pixel values from 0 to 1
            img_normalized = img_resized / 255.0

            # 5. Reshape for the model
            # The model expects a 4D tensor: (batch_size, height, width, channels)
            img_final = img_normalized.reshape(1, 28, 28, 1)

            # 6. Make prediction
            prediction = model.predict(img_final)
            predicted_digit = np.argmax(prediction)
            confidence = np.max(prediction)

            st.success(f"## Predicted Digit: {predicted_digit}")
            st.metric(label="Confidence", value=f"{confidence * 100:.2f}%")

            st.write("Here's how the model saw your drawing (28x28):")
            st.image(img_normalized, caption="Processed Image", width=140)

        elif model is None:
            st.error("Model is not loaded. Cannot predict.")
        else:
            st.warning("Please draw a digit on the canvas first.")