# -*- coding: utf-8 -*-
"""part3_troubleshooting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/143rkybkVtW8Sth--ljAq8s8GK18IqujB
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
import numpy as np

print("--- Part 3: Troubleshooting Challenge ---")

# --- 1. Load and Preprocess Data ---
# We load the data just as we did in Task 2
try:
    (x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

    # Normalize and reshape
    x_train, x_test = x_train / 255.0, x_test / 255.0
    x_train = x_train.reshape(-1, 28, 28, 1)
    x_test = x_test.reshape(-1, 28, 28, 1)

    print("MNIST data loaded and preprocessed successfully.")

except Exception as e:
    print(f"Error loading data: {e}")
    print("Please check your internet connection or TensorFlow installation.")
    exit()

# --- 2. The Buggy Code  ---
#
# Below is a non-runnable block of text showing the buggy code.
# The bug is that a 'Flatten' layer is missing between
# the 'MaxPooling2D' layer and the 'Dense' layer.
#
# This causes a 'ValueError' because the 3D output of the conv/pool layers
# (shape: (None, 13, 13, 32)) doesn't match the 1D input
# expected by the Dense layer (shape: (None, <features>)).
#
'''
### --- BUGGY CODE(it will not run) --- ###

buggy_model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D((2, 2)),

    # BUG: MISSING Flatten() LAYER

    # This Dense layer expects a 1D vector, but gets a 3D tensor
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

buggy_model.compile(optimizer='adam',
                    loss='sparse_categorical_crossentropy',
                    metrics=['accuracy'])

# This line would crash with a ValueError:
# buggy_model.fit(x_train, y_train, epochs=1)
### --- END OF BUGGY CODE --- ###
'''

# --- 3. The Fixed Code (This will run) ---

print("\nInitializing the FIXED model architecture...")

model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D((2, 2)),

    # THE FIX: Added a Flatten layer here
    # This unrolls the 3D feature map (13x13x32) into a 1D vector
    Flatten(),

    # Now this Dense layer receives the 1D vector it expects
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile the fixed model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

print("Model compiled successfully. The bug is fixed.")
model.summary()

# Train the model for one epoch to prove it works
print("\n--- Training fixed model for 1 epoch ---")
history = model.fit(x_train, y_train, epochs=1, validation_data=(x_test, y_test))

print("\n--- Troubleshooting Challenge Complete ---")
print("The model trained successfully, indicating the dimension mismatch is resolved.")